/*
 * HandleMdiArea.h
 *
 *  Created on: Jan 27, 2009
 *      Author: Zaixian Xie
 */

/*
 * class HandleMdiArea manages multiple windows
 * generated by QMdiArea
 */
#ifndef HANDLEMDIAREA_H_
#define HANDLEMDIAREA_H_

#include <QMdiArea>

class HandleMdiArea {
public:
	HandleMdiArea();
	virtual ~HandleMdiArea();

private:
	QMdiArea* m_mdiArea;

public:
	void setMdiArea(QMdiArea* mdiArea);
	QMdiArea* getMdiArea();
};

#endif /* HANDLEMDIAREA_H_ */
