/*
 * OkcDataModifierClusterColor.h
 *
 *  Created on: Jul 14, 2009
 *      Author: Zaixian Xie
 */

/*
 * Class OkcDataModifierClusterColor contains a vector
 * to represent the color for the cluster node.
 * The value is only a index between 0 and 1.
 * It should be mapped by class VisualMap to a real color
 * based on color manager.
 * It should be attached to an OkcData generated by a SBBOperator
 */

#ifndef OKCDATAMODIFIERCLUSTERCOLOR_H_
#define OKCDATAMODIFIERCLUSTERCOLOR_H_

#include <vector>
#include "data/multidim/OkcDataModifier.h"

class OkcData;

class OkcDataModifierClusterColor : public OkcDataModifier {
public:
	OkcDataModifierClusterColor();
	OkcDataModifierClusterColor(OkcData* okcdata);
	virtual ~OkcDataModifierClusterColor();

private:
	std::vector<double> m_color;

public:
	// return the modifier type
	XmdvTool::MODIFIERTYPE getModifierType();

	// Initialize the highlighted array,
	// its length is data_size of the OkcData
	void initColorArr();
	void setColor(int i, double color);
	double getColor(int i);

	// Return a reference to the color array
	std::vector<double> &getColorArr();

	// Add a color value to the end of array
	void insertTail(double color);

	void copyFrom(const OkcDataModifierClusterColor* copy);
	// overloading the operator "="
	void operator=(const OkcDataModifierClusterColor &copy);


};

#endif /* OKCDATAMODIFIERCLUSTERCOLOR_H_ */
