/*
 * OkcDataModifierClusterEntries.h
 *
 *  Created on: Jul 23, 2009
 *      Author: Zaixian Xie
 */

/*
 * Class OkcDataModifierClusterEntries contains a vector
 * to represent the number of entries (leaf) contained by the cluster node.
 * It should be attached to an OkcData generated by a SBBOperator
 */

#ifndef OKCDATAMODIFIERCLUSTERENTRIES_H_
#define OKCDATAMODIFIERCLUSTERENTRIES_H_

#include <vector>
#include "data/multidim/OkcDataModifier.h"

class OkcData;

class OkcDataModifierClusterEntries : public OkcDataModifier {
public:
	OkcDataModifierClusterEntries();
	OkcDataModifierClusterEntries(OkcData* okcdata);
	virtual ~OkcDataModifierClusterEntries();

private:
	std::vector<int> m_entries;

public:
	// return the modifier type
	XmdvTool::MODIFIERTYPE getModifierType();

	// Initialize the highlighted array,
	// its length is data_size of the OkcData
	void initEntriesArr();
	void setEntries(int i, int entries);
	int getEntries(int i);

	// Return a reference to the color array
	std::vector<int> &getEntriesArr();

	// Add a color value to the end of array
	void insertTail(int entries);

	// Get the number of all entries in the cluster of the current levels
	int getTotalEntries();

	void copyFrom(const OkcDataModifierClusterEntries* copy);
	// overloading the operator "="
	void operator=(const OkcDataModifierClusterEntries &copy);
};

#endif /* OKCDATAMODIFIERCLUSTERENTRIES_H_ */
